### ISSUE TITLE
Show original time when playing recordings

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#37]
When you increase the speed of the replay, the stopwatch will not increase it's speed. If you have a specific time you have no chance to find the scene.
![grafik](https://user-images.githubusercontent.com/35230554/97920658-0ef2fe00-1d5a-11eb-9a99-fdf6e76cfbda.png)

The stopwatch should be synchronized.

**Comment by maxmitti** [comment]
The "play time" display (the one in the top right) is not supposed to correlate with the actual amount of frames passed, as you might also notice during heavy lag or speedup in normal game play.
It just displays the wall time spent during which the game time actually progresses (i.e. not paused, not stuck due to network lag).

The closest you could get without changing anything is by looking at the Tick counter in the bottom bar of the F4 dialog.
(The tick counter relates to the frame counter by factor 1 : control rate.)
I always use that to debug / inspect various things captured in recordings.

**Comment by Somebodyisnobody** [comment]
> The closest you could get without changing anything is by looking at the Tick counter in the bottom bar of the F4 dialog.
(The tick counter relates to the frame counter by factor 1 : control rate.)
That's a solution. Didn't know about that feature. 👍
