### ISSUE TITLE
IPv6-Support

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#7]
At the moment, LegacyClonk only supports IPv4. While there are less IPv4 addresses than people on earth, many providers implemented a procedure where serval customers use one IPv4 address. This procedure is called "DS-Lite" and causes that many players are not able to host because the NATted IPv4-tunnel has no forwarded ports.

With an IPv6-clonk networkstack every DS-Lite-user would be able to host a game. Maybe also the [masterserver](https://github.com/clonkspot/league) needs to be adjusted.

The goal is a fully working, merged IPv6-clonk networkstack with a compatible masterserver.

The license is still the ISC

Edit: maxmitti is right, I just didn't want to go too far.

**Comment by maxmitti** [comment]
It would be best if the implementation would include some abstraction layer such that later changes or additional communication protocols can be added easily, for example for tunneling.

Just for further clarification, NATting many customers to only a few external IP addresses on the provider side alone is not called DS-Lite. DS-Lite is providing the combination of real IPv6 and NATted IPv4. On the other hand, at least in Austria the mobile internet providers that I know only provide NATted IPv4 without IPv6.

But keep in mind that without further additions, only clients which have internet supporting IPv6 can join to DS-Lite hosts, whereas IPv4-only clients can't anyway.

**Comment by Fulgen301** [comment]
Closed in 9ac72c034c5854566d98a9cca282edf917c16816

**Comment by Fulgen301** [comment]
Reopened because of the bounty.

**Comment by frederico-miranda** [comment]
Hello. After doing slight changes to the source code (the type "StdCopyStrBuf" is not defineocod anywhere, so I changed all references to this undeclared type to the declared type "StdStrBuf"), I've managed to built it (screenshot [#1](https://ibb.co/VgL7CLZ)) and run it after grabbing the required files as instructed (screenshot  [#2](https://ibb.co/RTjdRKh),[#3](https://ibb.co/8Y6VjJj),[#4](https://ibb.co/9wRPfks)).

I'm interested in [this bounty](https://www.bountysource.com/issues/77414793-ipv6-support). "ipv6 support", "abstraction layer such that additional communication protocols can be added easily": I think I can develop a solution that can fulfil these criteria. As a starting point, a server can exchange information with clients using IPv4 or IPv6 simultaneously (screenshot [#5](https://ibb.co/dD7Q8Gn)), which is useful for games, because it would be disappointing if a player base gets fragmented by IPv4 xor IPv6.

I'm writing this brief but polite presentation letter because even though a bounty is publicly visible, there might exist the expectation that someone already in close association with the project attempts to get it (which is not my case: before the publication of this bounty, I did not know of this  game), so I'd humbly like to know things clearly upfront.

**Comment by Fulgen301** [comment]
Hello @frederico-miranda!
We appreciate your interest in this manner. However, I have to remark that [IPv6 support has already been implemented ](https://github.com/legacyclonk/LegacyClonk/commit/93827ffbafa6e39650c9b813830e0f85faaedb50) - this issue is only open in order to sort out affairs regarding to the bounty.

**Comment by Somebodyisnobody** [comment]
@frederico-miranda Yeah it was a bit mixed up, actually I wanted to create the bounty first and then see who wants to implement ipv6. But at the same time the developers started to implement ipv6. So the issue was only reopened, so that the players, who want to give a reward for it, can donate via bountysource. Sorry for your trouble :/
